### ISSUE TITLE
Can't download dataset

### ISSUE THREAD

**Issue by msp3887** [kaistmm/VoxMM#2]
Hello, Thanks for great work.
I want to download dataset on project page https://mm.kaist.ac.kr/projects/voxmm/
But [download link](https://cn01.mmai.io/keyreq/voxmm) can't access and error message like under screenshot.
I'd like to ask for your confirmation, Thanks.
<img width="783" alt="SCR-20241121-qolk" src="https://github.com/user-attachments/assets/6bf60aa5-20f0-489c-851d-6c46f2534b0d">

**Comment by joonson** [comment]
It was a temporary server problem, the link should be working now.

**Comment by minsik-h** [comment]
Thank you for your quick confirmation.

**Comment by msp3887** [comment]
Thank you for your quick confirmation.
